### DISCUSSION TITLE
Using local Minio S3 service to store EDC Asset files

### DISCUSSION THREAD

**Discussion by skante93** [eclipse-edc/Connector#3831] [Q&A]
I am not very used to working with Java much less gradle, so my questions might be lacking and I apologize for that in advance.

I recently followed the [transfer 05](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-05-file-transfer-cloud) example in the Samples repository.
I tried to rework it so : 
* it uses file system vault 
* and it connects to a local Minio server, rather than AWS.

This is what I attempted : 
* cloned the samples repository
* replaced (line 31) <code>implementation(libs.edc.vault.azure)</code> with <code>implementation(libs.edc.vault.filesystem)</code> in the [gradle build file of the consumer](https://github.com/eclipse-edc/Samples/blob/main/transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts)
* then built that connector like so:
```bash
docker run -it --rm -v $(pwd)/Samples:/data -w /data gradle:jdk17 \
   ./gradlew transfer:transfer-05-file-transfer-cloud:cloud-transfer-consumer:build
```
* afterwards, I created the following vault file
```
aws-key=<MY ACCESS_KEY_ID>
aws-secret=<MY ACCESS_SECRET_KEY>
```
* then I created two connectors from the following docker compose stack:
```yaml
# The ./resources folder:
# ├── connector.jar               <--- Gradle built previously
# ├── keystore.jks
# └── vault.properties

provider:
    image: openjdk
    volumes:
      - ./resources:/app
    command:
      - java
      - -jar
      - /app/connector.jar
    environment:
      EDC_AWS_ACCESS_KEY: aws-key
      EDC_AWS_SECRET_ACCESS_KEY: aws-secret
      EDC_AWS_ENDPOINT_OVERRIDE: http://minio:9000                # <---- Minio Address
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_PARTICIPANT_ID: provider
      WEB_HTTP_PORT: 9191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 9192
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 9292
      WEB_HTTP_PROTOCOL_PATH: /protocol
      EDC_API_AUTH_KEY: password
      EDC_DSP_CALLBACK_ADDRESS: http://provider:9292/protocol
    ports:
      - 9191:9191
      - 9192:9192
      - 9292:9292

  consumer:
    image: openjdk
    volumes:
      - ./example:/example
      - ./resources:/app
    command:
      - java
      - -jar
      - /app/connector.jar
    environment:
      EDC_AWS_ACCESS_KEY: aws-key
      EDC_AWS_SECRET_ACCESS_KEY: aws-secret
      EDC_AWS_ENDPOINT_OVERRIDE: http://minio:9000              # <---- Minio Address
      EDC_VAULT: /app/vault.properties
      EDC_KEYSTORE: /app/keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_PARTICIPANT_ID: consumer
      WEB_HTTP_PORT: 8181
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 8182
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 8282
      WEB_HTTP_PROTOCOL_PATH: /protocol
      EDC_API_AUTH_KEY: password
      EDC_DSP_CALLBACK_ADDRESS: http://consumer:8282/protocol
    ports:
      - 8181:8181
      - 8182:8182
      - 8282:8282
```

The connectors start without any issue.

The on the provider, using its management API I created the following Asset:

```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "assetId",
  "properties": {
    "name": "Snowy stuff",
    "contenttype": "image/jpeg"
  },
  "dataAddress": {
    "type": "DataAddress",
    "properties": {
      "type": "AmazonS3",
      "name": "snow.jpg",
      "region": "us-east-1",
      "bucketName": "edc-test",
      "endpointOverride": "http://minio:9000"
    }
  }
}
```
Of course I made sure to have a bucket "edc-test" beforehand containing a "snow.jpg" file.
Eveything went smoothly untli I tried to initiate a transfer between the consumer and the provider. The transfer looks like this:

```json
{
  "@context": {
    "@vocab":  "https://w3id.org/edc/v0.0.1/ns/"
  },
  "counterPartyAddress": "http://provider:9292/protocol",
  "protocol": "dataspace-protocol-http",
  "connectorId": "consumer",
  "assetId": "assetId",
  "contractId": "${agreementId}",                                           <--- Agreement ID
  "dataDestination":  {
    "type": "AmazonS3",
    "region": "us-east-1",
    "name": "snow-copy.jpg",
    "bucketName": "edc-test-recipient",
    "endpointOverride": "http://minio:9000"
  },
  "transferType": {
    "contentType": "image/jpeg",
    "isFinite": true
  }
}
```
So far as I can tell the transfer fails before the provider even gets to do anything, because the consumer himself does not appear to be able to setup the "edc-test-recipient" successfully. I found it was due to an error 400 from Minio (operation seems to be about <code>sts.AssumeRole</code>). Anyway after some digging this is what I found the proper error message to be:
```xml
<?xml version="1.0" encoding="UTF-8"?>.
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
	<Error>
		<Type></Type>
		<Code>MissingParameter</Code>
		<Message>Invalid STS API version 2010-05-08, expecting 2011-06-15</Message>
	</Error>
	<RequestId>17B15489AF9D1319</RequestId>
</ErrorResponse>
```

Has anyone encountered something similar? Any help would be wellcomed
