### ISSUE TITLE
Asset Openapi Spec of Data Managment API uses objects where it should be string

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3188]
```
    Asset:
      type: object
      properties:
        createdAt:
          type: integer
          format: int64
          example: null
        id:
          type: string
          example: null
        privateProperties:
          type: object
          additionalProperties:
            type: object
            example: null
          example: null
        properties:
          type: object
          additionalProperties:
            type: object
            example: null
          example: null
      example: null

```

Latest version
https://raw.githubusercontent.com/eclipse-edc/Connector/2ded962d1ae67184c83c3ab724852424f7292e7d/resources/openapi/openapi.yaml

I think the `properties` (same for `privateProperties`) should be:
```
additionalProperties:
  type: string
```

because as I understood the content should be:
```
"mykey": "myvalue"
```
instead of:
```
"mykey": { "myotherkey": "myvalue"}
```
Any thoughts?

----
Matthias Binzer
